# Generated by Django 4.0.5 on 2022-06-20 23:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_assignment_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
