# Generated by Django 4.0.5 on 2022-06-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_discussion_user_alter_discussion_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='author',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
