# Generated by Django 4.0.5 on 2022-06-22 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_discussion_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='DiscussionReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120, null=True)),
                ('message', models.TextField(null=True)),
                ('post_date', models.DateTimeField(null=True)),
                ('discussion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussionreply', to='main.discussion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userreply', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
