# Generated by Django 4.0.5 on 2022-06-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_discussion_message_alter_todolist_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionreply',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
