# Generated by Django 4.0.5 on 2022-06-22 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_assignment_course_alter_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discusscourse', to='main.course'),
        ),
    ]
