# Generated by Django 4.0.5 on 2022-06-23 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
    ]
