# Generated by Django 4.0.5 on 2022-06-23 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_course_end_date_remove_course_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='assignments',
        ),
        migrations.RemoveField(
            model_name='module',
            name='teacher',
        ),
        migrations.AddField(
            model_name='assignment',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asmtmodule', to='main.module'),
        ),
    ]
