# Generated by Django 4.0.5 on 2022-06-23 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_remove_module_assignments_remove_module_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachersmodule', to=settings.AUTH_USER_MODEL),
        ),
    ]
